### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by hlapp** [Imageomics/ai-explainability#2]
The repo needs a license to clarify copyright and terms of reuse. The following are useful resources for selecting a license:
- https://choosealicense.com
- Morin, A., Urban, J., & Sliz, P. (2012). [A Quick Guide to Software Licensing for the Scientist-Programmer](https://doi.org/10.1371/journal.pcbi.1002598). PLoS Computational Biology, 8(7), e1002598.

I would suggest using the MIT License. It is a [OSI-compliant](https://opensource.org) permissive, non-viral license and is among those imposing the least restrictions on reuse.

**Comment by a-chow-cse** [comment]
As we will be using or extending other existing GitHub projects, and based on the guideline, I agree that we should use MIT license (I looked into some large GitHub projects, and most have MIT one)
![Screenshot from 2023-04-04 20-58-08](https://user-images.githubusercontent.com/10743417/229955340-7abc8801-3718-43ef-9481-056179654a55.jpg)

**Comment by DavidCarlyn** [comment]
I Like MIT, but I'm going to look into [BSD 3 license](https://opensource.org/license/BSD-3-clause/) first. If any of you have information on this license, comments are appreciated.

**Comment by hlapp** [comment]
> I'm going to look into [BSD 3 license](https://opensource.org/license/BSD-3-clause/) first. If any of you have information on this license, comments are appreciated.

It's a fine license, and is also non-viral, OSI-compliant, and similarly unrestrictive as the MIT license.

The BSD-3 license includes a clause on prohibiting use of the copyright holder's name to endorse a derived software product, whereas the MIT does not say anything about endorsement restrictions. If you feel that's important then a BSD-3 license may be preferable.

**Comment by thompsonmj** [comment]
Addressed by https://github.com/Imageomics/ai-explainability/pull/21
